class logical_operators:
  all = 'ALL '
  and = 'AND '
  any = 'ANY '
  exists = 'EXISTS '
  between = 'BETWEEN '
  like = 'LIKE '
  not_operator = 'NOT '
  or = 'OR '
  is_null = 'IS NULL '
  unique = 'UNIQUE '
